export default {
    ADD_TODO: 'ADD_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    TOGGLE_TODO: 'TOGGLE_TODO',

    ADD_CARD_TO_COMPARE: 'ADD_CARD_TO_COMPARE',
    REMOVE_CARD_TO_COMPARE: 'REMOVE_CARD_TO_COMPARE',
    TOGGLE_CARD_SELECTION: 'TOGGLE_CARD_SELECTION',

    INCREASE_CARD_LEVEL: 'INCREASE_CARD_LEVEL',
    DECREASE_CARD_LEVEL: 'DECREASE_CARD_LEVEL',
};
