export default {
    ADD_TODO: 'ADD_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    TOGGLE_TODO: 'TOGGLE_TODO',

    SELECT_CARD: 'SELECT_CARD',
    ADD_COMPARE_CARD: 'ADD_COMPARE_CARD',
    REMOVE_COMPARE_CARD: 'REMOVE_COMPARE_CARD',
    TOGGLE_CARD_SELECTION: 'TOGGLE_CARD_SELECTION',
};
